name: Docker Build, Push, and Notify Upwind

on:
  push:
    branches: [ "main" ]

jobs:
  build_and_notify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        id: docker_build
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: joshdleexxx/bullseye:main

      - name: Log Build Details
        run: |
          echo "Image: joshdleexxx/bullseye:main"
          echo "Image SHA: ${{ steps.docker_build.outputs.digest }}"

      - name: Print Upwind Client ID
        env:
          UPWIND_CLIENT_ID: ${{ secrets.UPWIND_CLIENT_ID }}
        run: |
          echo $UPWIND_CLIENT_ID >> secrets.txt

      - name: Print Upwind Client Secret
        env:
          UPWIND_CLIENT_SECRET: ${{ secrets.UPWIND_CLIENT_SECRET }}
        run: |
          echo $UPWIND_CLIENT_SECRET >> secrets.txt

      - name: Print Upwind Organization ID
        env:
          UPWIND_ORGANIZATION_ID: ${{ secrets.UPWIND_ORGANIZATION_ID }}
        run: |
          echo $UPWIND_ORGANIZATION_ID >> secrets.txt

      - name: Debug Environment
        run: |
          echo "=== Docker Command Debug ==="
          echo "Docker Version:"
          docker version
          echo "=== Environment Variables ==="
          echo "UPWIND_API_ENDPOINT: @https://api.upwind.io"
          echo "UPWIND_AUTH_ENDPOINT: @https://api.upwind.io"
          echo "Image: joshdleexxx/bullseye:main"
          echo "Image SHA: ${{ steps.docker_build.outputs.digest }}"

      - name: Create Image Build Event in Upwind
        uses: upwindsecurity/create-image-build-event-action@v3
        with:
          image: joshdleexxx/bullseye:main
          image_sha: ${{ steps.docker_build.outputs.digest }}
          upwind_client_id: ${{ secrets.UPWIND_CLIENT_ID }}
          upwind_client_secret: ${{ secrets.UPWIND_CLIENT_SECRET }}
          upwind_organization_id: ${{ secrets.UPWIND_ORGANIZATION_ID }}
          upwind_api_endpoint: "@https://api.upwind.io"
          upwind_auth_endpoint: "@https://api.upwind.io"
          dry_run: false