name: Docker Build, Push, and Notify Upwind

on:
  push:
    branches:
      - '**'  # matches every branch
  pull_request:
    branches:
      - '**'  # matches every branch

# Add permissions block
permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  build_and_notify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        id: docker_build
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: joshdleexxx/bullseye:main

      - name: Log Build Details
        run: |
          echo "Image: joshdleexxx/bullseye:main"
          echo "Image SHA: ${{ steps.docker_build.outputs.digest }}"

      - name: Shift Left Image Scan
        id: scan
        uses: upwindsecurity/shiftleft-create-image-scan-event-action@main
        with:
          upwind_client_id: ${{ secrets.UPWIND_CLIENT_ID }}
          upwind_client_secret: ${{ secrets.UPWIND_CLIENT_SECRET }}
          docker_image: "joshdleexxx/bullseye:main"
          pull_image: false

      - name: Create Scan Results Comment
        uses: actions/github-script@v7
        if: github.event_name == 'pull_request'
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const scanOutput = `${{ steps.scan.outputs.scan_result }}`;
            
            // Parse the scan output to get vulnerability counts
            const criticalMatch = scanOutput.match(/(\d+)\s+Critical/);
            const highMatch = scanOutput.match(/(\d+)\s+High/);
            const mediumMatch = scanOutput.match(/(\d+)\s+Medium/);
            const lowMatch = scanOutput.match(/(\d+)\s+Low/);
            const unclassifiedMatch = scanOutput.match(/(\d+)\s+Unclassified/);
            
            const output = `
            ## 🔒 Upwind Security Scan Results
            
            Found vulnerabilities in image joshdleexxx/bullseye:main:
            
            - 🔴 **${criticalMatch ? criticalMatch[1] : 0} Critical**
            - 🟠 **${highMatch ? highMatch[1] : 0} High**
            - 🟡 **${mediumMatch ? mediumMatch[1] : 0} Medium**
            - 🔵 **${lowMatch ? lowMatch[1] : 0} Low**
            - ⚪ **${unclassifiedMatch ? unclassifiedMatch[1] : 0} Unclassified**
            
            <details>
            <summary>Full Scan Results</summary>
            
            \`\`\`
            ${scanOutput}
            \`\`\`
            </details>
            
            [View run details](${process.env.GITHUB_SERVER_URL}/${process.env.GITHUB_REPOSITORY}/actions/runs/${process.env.GITHUB_RUN_ID})
            `;
            
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            });

      - name: Shift Left Image Publish
        uses: upwindsecurity/shiftleft-create-image-publish-event-action@main
        with:
          upwind_client_id: ${{ secrets.UPWIND_CLIENT_ID }}
          upwind_client_secret: ${{ secrets.UPWIND_CLIENT_SECRET }}
          docker_image: "joshdleexxx/bullseye:main"