name: Docker

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  UPWIND_URL: https://agent.upwind.io/v1/org_123/delivery/argo-cd

jobs:
  push_to_registries:
    name: Push Docker image to multiple registries
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Log in to the GitHub Container Registry (GHCR)
      - name: Log in to the Container registry (GHCR)
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Extract metadata (tags, labels) for Docker
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: |
            joshdleexxx/testing
            ghcr.io/${{ github.repository }}

      # Build and push Docker images to both registries
      - name: Build and push Docker images
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      # Notify Upwind
      - name: Notify Upwind
        env:
          UPWIND_TOKEN: ${{ secrets.UPWIND_TOKEN }}
        run: |
          CURRENT_TIME=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
          curl -X POST \
            ${{ env.UPWIND_URL }} \
            -H 'Content-Type: application/json' \
            -H "Authorization: Bearer ${UPWIND_TOKEN}" \
            -d "{
              \"resource_name\": \"my-app\",
              \"resource_namespace\": \"default\",
              \"resource_kind\": \"Application\",
              \"deploy_started_at\": \"${CURRENT_TIME}\",
              \"deploy_finished_at\": \"${CURRENT_TIME}\",
              \"sync_data\": {
                \"status\": \"created\",
                \"revision\": \"${{ github.sha }}\",
                \"path\": \"my-app\",
                \"repo_url\": \"${{ github.server_url }}/${{ github.repository }}\"
              }
            }"
