name: Docker Build, Push, and Notify Upwind

on:
  push:
    branches:
      - '**'  # matches every branch
  pull_request:
    branches:
      - '**'  # matches every branch

# Add permissions block
permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  build_and_notify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        id: docker_build
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: joshdleexxx/bullseye:main

      - name: Log Build Details
        run: |
          echo "Image: joshdleexxx/bullseye:main"
          echo "Image SHA: ${{ steps.docker_build.outputs.digest }}"

      - name: Shift Left Image Scan
        id: scan
        run: |
          # Create a file to store the scan output
          SCAN_OUTPUT_FILE="scan_output.txt"
          
          # Run the scan and capture its output
          sudo /home/runner/work/nginx-example-actions/nginx-example-actions/shiftleft image \
            --source=GITHUB_ACTIONS \
            --initiator=${GITHUB_TRIGGERING_ACTOR} \
            --upwind-uri=upwind.io \
            --upwind-client-id=${{ secrets.UPWIND_CLIENT_ID }} \
            --upwind-client-secret=${{ secrets.UPWIND_CLIENT_SECRET }} \
            --docker-image "joshdleexxx/bullseye:main" \
            --commit-sha ${GITHUB_SHA} \
            --branch ${GITHUB_REF} \
            --repository ${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY} \
            --docker-user="" \
            --docker-password="" \
            --debug=false \
            --docker-pull=false | tee $SCAN_OUTPUT_FILE

      - name: Create PR Comment
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const scanOutput = fs.readFileSync('scan_output.txt', 'utf8');
            
            const output = `## 🔒 Upwind Security Scan Results

            \`\`\`
            ${scanOutput}
            \`\`\`
            
            [View full details](${process.env.GITHUB_SERVER_URL}/${process.env.GITHUB_REPOSITORY}/actions/runs/${process.env.GITHUB_RUN_ID})`;
            
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            });

      - name: Shift Left Image Publish
        uses: upwindsecurity/shiftleft-create-image-publish-event-action@main
        with:
          upwind_client_id: ${{ secrets.UPWIND_CLIENT_ID }}
          upwind_client_secret: ${{ secrets.UPWIND_CLIENT_SECRET }}
          docker_image: "joshdleexxx/bullseye:main"