name: Docker and Notify Upwind

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  UPWIND_AUTH_ENDPOINT: https://auth.upwind.io/oauth/token
  UPWIND_API_ENDPOINT: https://agent.upwind.io/v1
  UPWIND_ORGANIZATION_ID: org_o82q2EUg6mFM1apa
  DOCKERHUB_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKERHUB_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  UPWIND_CLIENT_ID: ${{ secrets.UPWIND_CLIENT_ID }}
  UPWIND_CLIENT_SECRET: ${{ secrets.UPWIND_CLIENT_SECRET }}
  IMAGE_NAME: joshdleexxx/testing

jobs:
  build_push_notify:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ env.DOCKERHUB_PASSWORD }}

      - name: Build and push Docker image to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ${{ env.IMAGE_NAME }}

      - name: Authenticate with Upwind
        id: upwind_auth
        run: |
          response=$(curl -s --location "${{ env.UPWIND_AUTH_ENDPOINT }}/oauth/token" \
          --header "Content-Type: application/x-www-form-urlencoded" \
          --data-urlencode "grant_type=client_credentials" \
          --data-urlencode "audience=${{ env.UPWIND_API_ENDPOINT }}" \
          --data-urlencode "client_id=${{ env.UPWIND_CLIENT_ID }}" \
          --data-urlencode "client_secret=${{ env.UPWIND_CLIENT_SECRET }}")
          echo "::set-output name=access_token::$(echo "$response" | jq -r '.access_token')"

      - name: Notify Upwind
        if: steps.upwind_auth.outputs.access_token
        run: |
          IMAGE_SHA=$(docker inspect --format='{{index .RepoDigests 0}}' ${{ env.IMAGE_NAME }})
          curl -fsSL "${{ env.UPWIND_API_ENDPOINT }}/v1/organizations/${{ env.UPWIND_ORGANIZATION_ID }}/events" \
          --request POST \
          --header "Content-Type: application/json" \
          --header "Authorization: Bearer ${{ steps.upwind_auth.outputs.access_token }}" \
          --data '{
             "type": "image_build",
             "reporter": "GitHub Actions",
             "data": {
               "image": "${{ env.IMAGE_NAME }}",
               "commit_sha": "${{ github.sha }}",
               "repository": "${{ github.repository }}",
               "branch": "${GITHUB_REF_NAME}",
               "image_sha": "'"$IMAGE_SHA"'",
               "build_time": "$(date +'%Y-%m-%dT%H:%M:%SZ')"
             }
           }'
