name: Docker and Notify Upwind

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_push_notify:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image to Docker Hub
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          push: true
          tags: |
            joshdleexxx/testing:latest
            joshdleexxx/testing:${{ github.run_number }}

      # This is a new step to get the Docker Image SHA directly after build and push
      - name: Get Docker Image SHA
        id: get_image_sha
        run: echo "IMAGE_SHA=$(docker images --no-trunc --quiet joshdleexxx/testing:${{ github.run_number }})" >> $GITHUB_ENV

      - name: Create Image Build Event in Upwind
        uses: upwindsecurity/create-image-build-event-action@v1
        with:
          image: "joshdleexxx/testing:${{ github.run_number }}"
          image_sha: ${{ env.IMAGE_SHA }}
          upwind_api_endpoint: ${{ secrets.UPWIND_API_ENDPOINT }} # Assuming you have this as a secret if different from the default
          upwind_auth_endpoint: ${{ secrets.UPWIND_AUTH_ENDPOINT }} # Assuming you have this as a secret if different from the default
          upwind_client_id: ${{ secrets.UPWIND_CLIENT_ID }}
          upwind_client_secret: ${{ secrets.UPWIND_CLIENT_SECRET }}
          upwind_organization_id: ${{ secrets.UPWIND_ORGANIZATION_ID }}
