name: Docker Build, Push, and Notify Upwind

on:
  push:
    branches: [ "main" ]

jobs:
  build_and_notify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: joshdleexxx/bullseye:main

      - name: Echo Docker Image Details
        run: |
          echo "Image Name: joshdleexxx/bullseye:main"
          echo "Image Digest: ${{ steps.docker_build.outputs.digest }}"
      
      - name: Log image details
        run: |
          echo "Image: joshdleexxx/bullseye:main"
          echo "Image SHA: ${{ steps.docker_build.outputs.digest }}"

      - name: Echo Upwind Configuration
        run: |
          echo "Upwind Client ID: ${{ secrets.UPWIND_CLIENT_ID }}"
          echo "Upwind Organization ID: ${{ secrets.UPWIND_ORGANIZATION_ID }}"

      - name: Create Image Build Event in Upwind
        uses: upwindsecurity/create-image-build-event-action@v2
        with:
          image: "joshdleexxx/bullseye:main"
          image_sha: "${{ steps.docker_build.outputs.digest }}"
          upwind_client_id: ${{ secrets.UPWIND_CLIENT_ID }}
          upwind_client_secret: ${{ secrets.UPWIND_CLIENT_SECRET }}
          upwind_organization_id: ${{ secrets.UPWIND_ORGANIZATION_ID }}
      
      - name: Echo Upwind Configuration
        run: |
          echo "Image: joshdleexxx/bullseye:main"
          echo "Image SHA: ${{ steps.docker_build.outputs.digest }}"
          echo "Upwind Client ID: ${{ secrets.UPWIND_CLIENT_ID }}"
          echo "Upwind Organization ID: ${{ secrets.UPWIND_ORGANIZATION_ID }}"